"""Create contact table

Revision ID: 096708f70adc
Revises: 57b1ec04130e
Create Date: 2025-02-02 12:07:33.777467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096708f70adc'
down_revision = '57b1ec04130e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
